# Generated by Django 5.0.7 on 2024-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_student_user_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_studying',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
